version: "3.3"

services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    working_dir: /var/www/html
    volumes:
      - /srv/http/docker-wordpress.test/htdocs/wp-content:/var/www/html/wp-content
      - /srv/http/docker-wordpress.test/htdocs/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    environment:
   PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
volumes:
  db_data:
